version: '3.2'
services:
  php:
    image: php:7-fpm
    volumes:
      - ./public:/var/www

  nginx:
    image: nginx:latest
    volumes:
      - ./public:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - 5000:80
